In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
data= pd.read_csv('corona_tested_individuals_ver_0083.english.csv')

C:\Users\priya\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3165: DtypeWarning: Columns (7) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,


In [4]:
data.shape

(2742596, 10)

In [5]:
data.head()

test_date  cough  fever  sore_throat  shortness_of_breath  head_ache  \
0  2020-11-12      0      0            0                    0          0   
1  2020-11-12      0      1            0                    0          0   
2  2020-11-12      0      0            0                    0          0   
3  2020-11-12      0      0            0                    0          0   
4  2020-11-12      0      1            0                    0          0   

  corona_result age_60_and_above  gender         test_indication  
0      negative               No    male                   Other  
1      negative               No    male                   Other  
2      negative              Yes  female                   Other  
3      negative               No    male                   Other  
4      negative               No    male  Contact with confirmed

In [6]:
data['corona_result'].value_counts()


negative    2480403
positive     220975
other         41218
Name: corona_result, dtype: int64

In [7]:
data['corona_result'].replace({"other":"negative"},inplace = True)

In [8]:
data['corona_result'].value_counts()


negative    2521621
positive     220975
Name: corona_result, dtype: int64

In [9]:
y=data.iloc[:,6:7]

In [10]:
y

corona_result
0            negative
1            negative
2            negative
3            negative
4            negative
...               ...
2742591      negative
2742592      negative
2742593      negative
2742594      negative
2742595      negative

[2742596 rows x 1 columns]

In [11]:
data.drop(columns='corona_result',axis=0,inplace=True)

In [12]:
X = pd.get_dummies(data, columns = ['test_date','test_indication'])

In [13]:
X.age_60_and_above.unique()

array(['No', 'Yes', nan], dtype=object)

In [14]:
X['age_60_and_above'].mode()

0    No
dtype: object

In [15]:
# filling with most common clas
X= X.apply(lambda x: x.fillna(x.value_counts().index[0]))


In [16]:
X.age_60_and_above.unique()

array(['No', 'Yes'], dtype=object)

In [17]:
X.head()

cough  fever  sore_throat  shortness_of_breath  head_ache age_60_and_above  \
0      0      0            0                    0          0               No   
1      0      1            0                    0          0               No   
2      0      0            0                    0          0              Yes   
3      0      0            0                    0          0               No   
4      0      1            0                    0          0               No   

   gender  test_date_2020-03-11  test_date_2020-03-12  test_date_2020-03-13  \
0    male                     0                     0                     0   
1    male                     0                     0                     0   
2  female                     0                     0                     0   
3    male                     0                     0                     0   
4    male                     0                     0                     0   

   ...  test_date_2020-11-06  test_date_2020-11-07  test_date_2020-11-08  \
0  ...                     0                     0                     0   
1  ...                     0                     0                     0   
2  ...                     0                     0                     0   
3  ...                     0                     0                     0   
4  ...                     0                     0                     0   

   test_date_2020-11-09  test_date_2020-11-10  test_date_2020-11-11  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   test_date_2020-11-12  test_indication_Abroad  \
0                     1                       0   
1                     1                       0   
2                     1                       0   
3                     1                       0   
4                     1                       0   

   test_indication_Contact with confirmed  test_indication_Other  
0                                       0                      1  
1                                       0                      1  
2                                       0                      1  
3                                       0                      1  
4                                       1                      0  

[5 rows x 257 columns]

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(y)

C:\Users\priya\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


In [19]:
y

array([0, 0, 0, ..., 0, 0, 0])

In [20]:
X['shortness_of_breath'].value_counts()

0    2731579
1      11017
Name: shortness_of_breath, dtype: int64

In [21]:
# Assigning numerical values to age 60 
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X['age_60_and_above'] = labelencoder.fit_transform(X['age_60_and_above'])

In [22]:
X['gender'].head()

0      male
1      male
2    female
3      male
4      male
Name: gender, dtype: object

In [23]:
# Assigning numerical values to gender column

X['gender'] = labelencoder.fit_transform(X['gender'])

In [24]:
X['gender'].head()

0    1
1    1
2    0
3    1
4    1
Name: gender, dtype: int32

In [25]:
X.head()

cough  fever  sore_throat  shortness_of_breath  head_ache  \
0      0      0            0                    0          0   
1      0      1            0                    0          0   
2      0      0            0                    0          0   
3      0      0            0                    0          0   
4      0      1            0                    0          0   

   age_60_and_above  gender  test_date_2020-03-11  test_date_2020-03-12  \
0                 0       1                     0                     0   
1                 0       1                     0                     0   
2                 1       0                     0                     0   
3                 0       1                     0                     0   
4                 0       1                     0                     0   

   test_date_2020-03-13  ...  test_date_2020-11-06  test_date_2020-11-07  \
0                     0  ...                     0                     0   
1                     0  ...                     0                     0   
2                     0  ...                     0                     0   
3                     0  ...                     0                     0   
4                     0  ...                     0                     0   

   test_date_2020-11-08  test_date_2020-11-09  test_date_2020-11-10  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   test_date_2020-11-11  test_date_2020-11-12  test_indication_Abroad  \
0                     0                     1                       0   
1                     0                     1                       0   
2                     0                     1                       0   
3                     0                     1                       0   
4                     0                     1                       0   

   test_indication_Contact with confirmed  test_indication_Other  
0                                       0                      1  
1                                       0                      1  
2                                       0                      1  
3                                       0                      1  
4                                       1                      0  

[5 rows x 257 columns]

In [26]:

X['sore_throat'].value_counts()

0    2712512
1      30084
Name: sore_throat, dtype: int64

In [27]:
X['fever'].unique()

array([0, 1], dtype=int64)

In [28]:
X['head_ache'].value_counts()

0    2682655
1      59941
Name: head_ache, dtype: int64

In [29]:
X.shape


(2742596, 257)

In [30]:
X.head()

cough  fever  sore_throat  shortness_of_breath  head_ache  \
0      0      0            0                    0          0   
1      0      1            0                    0          0   
2      0      0            0                    0          0   
3      0      0            0                    0          0   
4      0      1            0                    0          0   

   age_60_and_above  gender  test_date_2020-03-11  test_date_2020-03-12  \
0                 0       1                     0                     0   
1                 0       1                     0                     0   
2                 1       0                     0                     0   
3                 0       1                     0                     0   
4                 0       1                     0                     0   

   test_date_2020-03-13  ...  test_date_2020-11-06  test_date_2020-11-07  \
0                     0  ...                     0                     0   
1                     0  ...                     0                     0   
2                     0  ...                     0                     0   
3                     0  ...                     0                     0   
4                     0  ...                     0                     0   

   test_date_2020-11-08  test_date_2020-11-09  test_date_2020-11-10  \
0                     0                     0                     0   
1                     0                     0                     0   
2                     0                     0                     0   
3                     0                     0                     0   
4                     0                     0                     0   

   test_date_2020-11-11  test_date_2020-11-12  test_indication_Abroad  \
0                     0                     1                       0   
1                     0                     1                       0   
2                     0                     1                       0   
3                     0                     1                       0   
4                     0                     1                       0   

   test_indication_Contact with confirmed  test_indication_Other  
0                                       0                      1  
1                                       0                      1  
2                                       0                      1  
3                                       0                      1  
4                                       1                      0  

[5 rows x 257 columns]

In [31]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2, random_state=1)

In [32]:
print(X_train)

         cough  fever  sore_throat  shortness_of_breath  head_ache  \
945529       0      0            0                    0          0   
2552683      1      0            0                    0          0   
1905075      0      0            0                    0          0   
1817578      0      0            0                    0          0   
697761       0      0            0                    0          0   
...        ...    ...          ...                  ...        ...   
836489       0      0            0                    0          0   
491263       0      0            0                    0          0   
2568076      0      0            0                    0          0   
491755       0      0            0                    0          0   
128037       0      0            0                    0          0   

         age_60_and_above  gender  test_date_2020-03-11  test_date_2020-03-12  \
945529                  0       1                     0                     0 

In [33]:
print(X_test)

         cough  fever  sore_throat  shortness_of_breath  head_ache  \
704399       0      0            0                    0          0   
335370       0      0            0                    0          0   
664830       0      0            0                    0          0   
2055610      0      0            0                    0          0   
1698752      0      0            0                    0          0   
...        ...    ...          ...                  ...        ...   
2677462      0      0            0                    0          0   
1486781      0      0            0                    0          0   
1388030      0      0            0                    0          0   
1544390      0      0            0                    0          0   
203472       0      0            0                    0          0   

         age_60_and_above  gender  test_date_2020-03-11  test_date_2020-03-12  \
704399                  0       0                     0                     0 

In [34]:
print(y_train)

[0 0 0 ... 0 0 0]


In [35]:
print(y_test)

[0 0 0 ... 0 0 0]


In [36]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy',random_state = 0)

In [37]:
classifier.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', n_estimators=10, random_state=0)

In [38]:
y_pred = classifier.predict(X_test)


In [39]:
y_pred



array([0, 0, 0, ..., 0, 0, 0])

In [40]:
y_test

array([0, 0, 0, ..., 0, 0, 0])

In [41]:
from sklearn.metrics import accuracy_score

In [42]:
accuracy_score(y_test, y_pred)

0.9421187923867863

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
classifier = LogisticRegression(random_state = 0 )

In [45]:
classifier.fit(X_train,y_train)

C:\Users\priya\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [46]:
y_pred = classifier.predict(X_test)

In [47]:
accuracy_score(y_test, y_pred)

0.9335065266535404

In [ ]:
# Training the SVM model on the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, y_train)



In [ ]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
accuracy_score(y_test, y_pred)